KEYWORD_MAP = {
    # Multi-word keywords (must come before single-word to match first)
    # Keywords
    ("Lež",): "False",
    ("Nic",): "None",
    ("Pravda",): "True",
    ("a",): "and",
    ("jako",): "as",
    ("vyčkat",): "await",
    ("rozbít",): "break",
    ("klasa",): "class",
    ("pokračovat",): "continue",
    ("smaž",): "del",
    ("jinkdyž",): "elif",
    ("jinak",): "else",
    ("kromě",): "except",
    ("konečně",): "finally",
    ("pro",): "for",
    ("od",): "from",
    ("když",): "if",
    ("dovézt",): "import",
    ("v",): "in",
    ("je",): "is",
    ("sirka",): "match",
    ("případ",): "case",
    ("nebo",): "or",
    ("přejdi",): "pass",
    ("povznes",): "raise",
    ("vrať",): "return",
    ("zkus",): "try",
    ("při",): "while",
    ("s",): "with",
    ("vynes",): "yield",

    # Builtins
    ("vytiskni",): "print",
}